language: go
go:
- "1.13"
script:
- export GO111MODULE=on
- GOOS=linux go build ./azblob
- GOOS=darwin go build ./azblob
- GOOS=windows go build ./azblob
- GOOS=solaris go build ./azblob
- go test -race -short -cover -v ./azblob
